version: "2"
services:
  web:
    image: nats
    network_mode: "host"
#    volumes:
#      - ./nats/nats.conf:/config/nats.conf
#    entrypoint: ["/gnatsd"]
#    command: ["-c", "/config/nats.conf"]
